const APP_ACTION_TYPE = {
  INIT: 1,
  LOCK_EMPLOYEE: 2,
  UNLOCK_EMPLOYEE: 3
};

const EMPLOYEE_ACTION_TYPE = {
  INIT: 1,
  LOCK_EMPLOYEE: 2,
  UNLOCK_EMPLOYEE: 3
};

export { APP_ACTION_TYPE, EMPLOYEE_ACTION_TYPE };
